backups/urls.py
from django.contrib import admin
from django.urls import path, include
from productivity.views import home
from rest_framework.routers import DefaultRouter
from productivity import api


router = DefaultRouter()
router.register('categories', api.CategoryViewSet)
router.register('projects', api.ProjectViewSet)
router.register('tasks', api.TaskViewSet)
router.register('addons', api.TaskAddonViewSet)
router.register('addonproviders', api.TaskAddonProviderViewSet)

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('backups/', include('logs.urls')),
    path('prod/', include('productivity.urls')),
    path('profile/', include('profiles.urls')),
    path('sync/', include('sync.urls')),
    path('api/', include(router.urls)),
    path('api/jira', api.JiraWebhook.as_view())
]

logs/urls.py
from django.urls import path

from logs import views

app_name = 'logs'

urlpatterns = [
    path('api/pr', views.Changelog.as_view()),
    path('api/', views.BackUpList.as_view()),
    path('prs/', views.pr_list, name='prs'),
    path('', views.BackUpListView.as_view(), name='backups')
]

productivity/urls.py
from django.urls import path

from productivity import views

app_name = 'prod'

urlpatterns = [
    path('today/', views.today, name='today'),
    path('week/', views.this_week, name='this_week'),
    path('today/refresh', views.tasks_today, name='refresh'),
    path('category/find', views.find_category, name='find_category'),
    path('category/create', views.create_category, name='create_category'),
    path('defaults/', views.tasks_in_default, name='defaults'),
    path('project/find', views.find_project, name='find_project'),
    path('project/create', views.create_project, name='create_project'),
    path('tasks/create', views.create_task, name='task_create'),
    path('tasks/delete', views.delete_task, name='task_delete'),
    path('tasks/<int:tid>/addon', views.add_new_addon, name='task_addon'),
    path('tasks/project/<str:pro>', views.find_by_project, name='by_project'),
    path('tasks/fu/<int:task>/<str:field>/<int:val>', views.task_fast_update, name='tfu'),
    path('tasks/fu/<int:task>/<str:field>/<str:val>', views.task_fast_update, name='tfu'),
    path('emails/', views.read_mails, name='mails'),
    path('emails/import', views.import_emails, name='import_mails'),
    path('events/import', views.import_events, name='import_events'),
    path('providers/create', views.CreateAddonProviderView.as_view(), name='provider_create'),
    path('providers/', views.ListAddonProviderView.as_view(), name='providers_list'),
    path('providers/update/<int:pk>', views.UpdateAddonProviderView.as_view(), name='providers_update'),
    path('projects/list', views.ProjectFastUpdateListView.as_view(), name='projects_quicklist'),
    path('categories/list', views.CategoryFastUpdateListView.as_view(), name='categories_quicklist'),
    path('task/<int:task>/list', views.task_text_fast_update_view, name='text_quicklist'),
    path("projects/", views.ProjectsView.as_view(), name="projects"),
    path("projects/new", views.generate_new_project, name='generate_project'),
    path("projects/delete/<int:pro>", views.delete_project, name='delete_project'),
    path("projects/partial", views.ListProjectView.as_view(), name="projects_list_partial"),
    path('projects/fu/<int:pro>/<str:field>/<int:val>', views.project_fast_update, name='pfu'),
    path('projects/fu/<int:pro>/<str:field>/<str:val>', views.project_fast_update, name='pfu'),
    path('projects/update/template/<int:pro>', views.project_update_view, name='project_update'),
    path("categories/", views.CategoriesView.as_view(), name="categories"),
    path("categories/new", views.generate_new_category, name='generate_category'),
    path("categories/partial", views.ListCategoriesView.as_view(), name="categories_list_partial"),
    path("categories/delete/<int:cat>", views.delete_category, name='delete_category'),
    path('categories/update/template/<int:cat>/<str:field>', views.category_update_view, name='cat_update'),
    path('categories/fu/<int:cat>/<str:field>/<str:val>', views.category_fast_update, name='cfu'),
    ]

productivity/models.py
from functools import cached_property

from markdown import markdown

from django.conf import settings
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.timezone import now


class TodoistManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super(TodoistManager, self).get_queryset().filter(todoist_id__isnull=False)


class Category(models.Model):
    """The categories of the projects."""
    name = models.CharField(max_length=20, unique=True)
    emoji = models.CharField(max_length=10)
    # TODO: Make this a unique together when it will relate to the user
    todoist_id = models.BigIntegerField(blank=True, null=True, unique=True)
    objects = models.Manager()
    todoist = TodoistManager()

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.emoji + " " + self.name

    @cached_property
    def tasks_count(self) -> int:
        """Total number of tasks associated with the category."""
        return self.task_set.count()


class ActiveProjectManager(models.Manager):
    """Manager that gets only active projects by default"""
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(is_active=True)


class Project(models.Model):
    """The tasks project model."""
    name = models.CharField(max_length=20, unique=True)
    color = models.CharField(max_length=8)
    # TODO: Make this a unique together when it will relate to the user
    todoist_id = models.BigIntegerField(blank=True, null=True, unique=True)
    objects = models.Manager()
    todoist = TodoistManager()
    is_active = models.BooleanField(default=True)
    active = ActiveProjectManager()

    def __str__(self) -> str:
        return "#" + self.name

    def remove_hex_prefix(self):
        """Removes the # on colors"""
        self.color = self.color.replace("#", "")

    @cached_property
    def tasks_count(self) -> int:
        """Total number of tasks associated with the project."""
        return self.task_set.count()

    @cached_property
    def repos_count(self) -> int:
        """Total number of repos associated with the project."""
        return self.repos.count()


class Task(models.Model):
    """Model to log tasks within the day"""
    created_at = models.DateTimeField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    task = models.CharField(max_length=400)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True,
                                blank=True)
    objects = models.Manager()
    # TODO: Make this a unique together when it will relate to the user
    todoist_id = models.BigIntegerField(blank=True, null=True)
    todoist = TodoistManager()

    class Meta:
        ordering = ['category', 'created_at']

    def __str__(self) -> str:
        return self.category.emoji + self.task

    def save(self, *args, **kwargs):
        if self.created_at is None:
            self.created_at = now()
        super(Task, self).save(*args, **kwargs)

    @property
    def rich_text(self) -> str:
        return markdown(self.task)

    def has_addon_in_task(self):
        """Checks whether the task has an addon inserted"""
        return ":" in self.task

    def extract_addons(self):
        for word in self.task.split(" "):
            if ":" in word:
                try:
                    sh = word.split(":")
                    prov = TaskAddonProvider.objects.get(shortcut=sh[0])
                except (ObjectDoesNotExist, MultipleObjectsReturned):
                    pass
                else:
                    self.create_addon(prov, word)
                finally:
                    self.task = self.task.replace(word, "")

        self.save()

    def create_addon(self, prov, word):
        sh = word.split(":")
        if sh[1] in ["", " ", None]:
            return None
        if sh[1].startswith('http'):
            TaskAddon.objects.create(
                task=self, provider=prov, url=word.split(sh[0] + ":")[1],
            )
        else:
            TaskAddon.objects.create(
                task=self, provider=prov, uid=word.split(sh[0] + ":")[1],
            )
        return None

    @property
    def pendulum_dt(self):
        """Returns the datetime in a pendulum class"""
        from pendulum.parser import parse
        return parse(str(self.created_at)).in_timezone(settings.TIME_ZONE)

    @property
    def date(self) -> str:
        """Returns the date the task was created"""
        return self.pendulum_dt.to_date_string()

    @property
    def time(self) -> str:
        """Returns the time the task was created"""
        return self.pendulum_dt.to_time_string()

    @property
    def datetime(self) -> str:
        """Returns the full datetime the issue was created"""
        return self.pendulum_dt.to_datetime_string()


class Gmail(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    from_address = models.CharField(max_length=200)
    subject = models.CharField(max_length=500)
    done = models.BooleanField(default=False)
    thread_id = models.CharField(max_length=50, unique=True)


class TaskAddonProvider(models.Model):
    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=40)
    color = models.CharField(max_length=8)
    shortcut = models.CharField(max_length=10, null=True, blank=True)
    base_url = models.URLField()

    @staticmethod
    def get_absolute_url() -> str:
        """Returns the list url of the model."""
        return reverse("prod:providers_list")

    def __str__(self):
        """Returns the representation string for the model."""
        return self.name

    def show_base_url(self, task):
        """Renders the template url into the file link."""
        return self.base_url.format(task=task)

    def remove_hex_prefix(self):
        """Removes the # on colors"""
        self.color = self.color.replace("#", "")


class TaskAddon(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    provider = models.ForeignKey(TaskAddonProvider, on_delete=models.CASCADE)
    uid = models.CharField(max_length=200)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.provider.name + ' for ' + self.task.__str__()

    def set_params(self) -> None:
        if self.url:
            self.uid = self.url.split('/')[-1]
        if self.uid and self.provider and not self.url:
            self.url = self.provider.show_base_url(self.task) + self.uid
        self.save()


@receiver(post_save, sender=Task)
def create_task_addon(sender, instance, created, **kwargs):
    if instance.has_addon_in_task() and instance.project:
        instance.extract_addons()


@receiver(post_save, sender=TaskAddon)
def set_addon_url(sender, instance, created, **kwargs):
    if created:
        instance.set_params()


@receiver(pre_save, sender=TaskAddonProvider)
@receiver(pre_save, sender=Project)
def removes_prefix_from_colors(sender, instance, **kwargs):
    instance.remove_hex_prefix()

productivity/views/addons.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView

from productivity.models import TaskAddonProvider


class CreateAddonProviderView(LoginRequiredMixin, CreateView):
    """Create a new addon provider"""

    model = TaskAddonProvider
    fields = ['name', 'icon', 'color', 'shortcut', 'base_url']


class ListAddonProviderView(LoginRequiredMixin, ListView):
    """Lists all available addon providers"""

    model = TaskAddonProvider


class UpdateAddonProviderView(LoginRequiredMixin, UpdateView):
    """Updates one or more of the below field on a dedicated view"""

    model = TaskAddonProvider
    fields = ['name', 'icon', 'color', 'shortcut', 'base_url']

productivity/views/categories.py
from typing import Union

from faker import Faker

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from productivity.models import Category


class CategoriesView(LoginRequiredMixin, TemplateView):
    """Static container view to list the categories."""

    template_name = "productivity/categories/list.html"


class ListCategoriesView(LoginRequiredMixin, ListView):
    """Renders the Category <li> element for each category."""

    model = Category
    queryset = Category.objects.all()
    template_name = "productivity/categories/_category.html"
    context_object_name = "categories"


@login_required
def category_update_view(request, cat: int, field: str):
    """Fast update for the category fields."""
    category = get_object_or_404(Category, id=cat)

    return render(request, "productivity/categories/_edit.html", {'cat': category, 'field': field})


@login_required
def delete_category(request, cat: int):
    """Deletes an existing category."""
    if not request.method == 'POST':
        return HttpResponseBadRequest()

    category = get_object_or_404(Category, id=cat)
    category.delete()

    return JsonResponse({'result': True, 'message': 'Task deleted'})


@login_required
def category_fast_update(request, cat: int, field: str, val: Union[int, str]):
    """Updates a task based on url fields."""
    if request.method != "POST":
        return HttpResponseBadRequest("Invalid http method")
    try:
        category = Category.objects.get(pk=cat)
        setattr(category, field, val)
        category.save(update_fields=[field])
    except Exception as e:
        result = {'result': False, 'message': str(e)}
    else:
        result = {'result': True, 'message': f'{field} successfully changed for {category.name}'}
    return JsonResponse(result)


@login_required
def generate_new_category(request):
    """Generates a placeholder category. This can be immediately editted in the list view."""
    fake = Faker()
    Faker.seed(0)
    Category.objects.create(name=fake.domain_word(), emoji="🍀")
    return JsonResponse({'result': True})

productivity/views/projects.py
from typing import Union

from faker import Faker

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import (HttpResponseBadRequest, HttpResponseNotFound,
                         JsonResponse)
from django.shortcuts import render
from django.views.generic import ListView, TemplateView

from productivity.models import Project


class ProjectsView(LoginRequiredMixin, TemplateView):
    """Renders the container view for the projects list."""

    template_name = "productivity/projects/list.html"


class ListProjectView(LoginRequiredMixin, ListView):
    """Renders the <li> element for all active projects."""

    model = Project
    queryset = Project.objects.exclude(is_active=False).order_by('name')
    template_name = "productivity/projects/_projects.html"
    context_object_name = "projects"


@login_required
def delete_project(request, pro: int):
    """Deletes an existing project."""
    if not request.method == 'POST':
        return HttpResponseBadRequest()
    try:
        project = Project.objects.get(id=pro)
    except ObjectDoesNotExist:
        return HttpResponseNotFound()
    else:
        project.delete()
    return JsonResponse({'result': True, 'message': 'Task deleted'})


@login_required
def project_update_view(request, pro: int):
    """Fast update template for the project model."""
    project = get_object_or_404(Project, id=pro)

    return render(request, "productivity/projects/_edit.html", {'project': project})


@login_required
def project_fast_update(request, pro: int, field: str, val: Union[int, str]):
    """Updates a task based on url fields."""
    if request.method != "POST":
        return HttpResponseBadRequest("Invalid http method")
    try:
        p = Project.objects.get(pk=pro)
        setattr(p, field, val)
        p.save(update_fields=[field])
    except Exception as e:
        result = {'result': False, 'message': str(e)}
    else:
        result = {'result': True, 'message': f'{field} successfully changed for #{p.name}'}
    return JsonResponse(result)


@login_required
def generate_new_project(request):
    """Generates a placeholder category. This can be immediately editted in the list view."""
    fake = Faker()
    Faker.seed(0)
    Project.objects.create(
        name=fake.domain_word(),
        color=fake.hex_color()
    )
    return JsonResponse({'result': True})

templates/productivity/_categories_select.html
<select class="field-container" name="category" id="category_update" data-action='tasks#taskFastUpdate' data-field='category_id'>
    <option disabled selected value>❓ category</option>
{% for category in categories %}
    <option value="{{category.id}}"> {{category.emoji}} {{category.name}}</option>
{% endfor %}
</select>

templates/productivity/_events.html
{% load productivity_extras %}
{% for event in events %}
<style>
.event_grid{
    display: inline-grid;
    grid-template-row: auto auto;
}
</style>

<li style="margin: 10px;">
    <span class="fa-layers fa-fw" style='margin-right: 10px; top: 8px'>
        <i class="fas fa-calendar fa-2x"></i>
        <span class="fa-layers-text fa-inverse" data-fa-transform="right-3 down-3"  style="font-weight:700">{{event.start.dateTime|day_of_date}}</span>
    </span>
    <span class='event_grid'>
        <span class='title_link'>    
            <strong>
                <a href="{{event.htmlLink}}" style='color: inherit; text-decoration: none'>{{event.summary}}</a>  
            </strong>
        </span>
        <span class="event_info">
            <i class="fas fa-map-marker"></i>
            {{event.location|truncatechars:33}}
            <i class="fas fa-users"></i> {{event.attendees|length}}
            <i class='text-primary'>{{event.organizer.email}}</i>
        </span>
    </span>
</li>

{% empty %}
<li><i>No events found</i></li>
{% endfor %}

templates/productivity/_projects_select.html
<select class="field-container" name="project" id="project_update" data-action='tasks#taskFastUpdate' data-field='project_id'>
    <option disabled selected value>project</option>
{% for project in projects %}
    <option value="{{project.id}}" style='color: #{{project.color}}'>#{{project.name}}</option>
{% endfor %}
</select>

templates/productivity/_task.html
<li class="tsk mt-2 ml-3" data-tasks-target='filterable' data-tasks-project="{{task.project.name}}" data-task="{{task.id}}">
    <span class="category model-container" data-model='categories' data-action="click->tasks#updateView">
    {{task.category.emoji}}
    </span>
    <span class="tsk-text"><a class="model-container" data-model='task/{{task.id}}' data-action="click->tasks#updateView">{{task.rich_text|safe}}</a></span>
    <span class='project model-container' style='color: #{{task.project.color}}' data-model='projects' data-action="click->tasks#updateView">
        {{task.project}}
    </span>
    {% if task.project.name == "default" %}
        <small>
            <a href="{% url 'prod:today' %}?date={{task.created_at.date|date:'Y-m-d'}}">{{task.datetime}}</a>
        </small>
    {% else %}
        <small>{{task.time}}</small>
    {% endif %}


    <span class='addons ml-3 d-block'>
        {% if task.taskaddon_set.all %}
            {% for addon in task.taskaddon_set.all %}
            <a target="_blank" href='{{addon.url}}' class="addon py-0">
                <img class='simpleicon' data-action='load->tasks#fixSimpleIconColor' data-color="#{{addon.provider.color}}"
                    height="16" width="16"
                    src="https://unpkg.com/simple-icons@v2/icons/{{addon.provider.icon}}.svg" />
            </a>
            {% endfor %}
        {% endif %}
        <div class='d-inline-block w-50' data-controller="addons" data-url="{% url 'prod:task_addon' task.id %}">
            <a class='addon py-0' data-action="click->addons#show">
                <i class="fas fa-plus-circle text-primary"></i>
            </a>
            <a class='addon py-0 tsk-delete' data-action='click->tasks#deleteTask' data-taskid="{{task.id}}">
                <i class="fas fa-times text-danger"></i>
            </a>
        </div>
    </span>
</li>

templates/productivity/_task_edit.html
<input class='input field-container' style='width: 700px' name="task" id="task_update" value='{{task.task}}' data-action='keyup->tasks#taskFastUpdate' data-field='task'>

templates/productivity/_taskaddon.html
<div class="task-addon-card" data-addons-target="addonCard">
    <button type="button" class="close" data-action='addons#hide' aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <form class='form-inline' action="{% url 'prod:task_addon' tid %}" method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
            <select class="form-control" name="pid">
                {% for provider in providers %}
                <option value="{{provider.id}}">{{provider.name}}</option>
                {% endfor %}
            </select>
            
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <input class="form-control" type="text" name='uid' placeholder='uid or link'>
        </div>
    </form>
    <div data-popper-arrow class='arrow'></div>
</div>

templates/productivity/defaults.html
{% extends "base.html"  %}

{% block content %}
<div data-controller='tasks' class="row my-5 justify-content-center">
  <div class="col-md-12 col-lg-8">
    <div class="card">
      <div class="card-header">
        <span id='titleDate'>
          Tasks in default project. Found ({{tasks|length}})
        </span>
      </div>
      <div class="card-body tasks" id='tasks'>
        {% include "productivity/todays_tasks.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/productivity/google_auth.html
<p>No google account found for current user</p>
<a href="{% url 'social:begin' 'google-oauth2'%}" class="btn btn-danger">Sign in with Google</a>

templates/productivity/taskaddonprovider_form.html
{% extends '_card.html' %}

{% block title %} Settings {% endblock title %}  

{% block card_body %}

<form action="" method="post">
{% csrf_token %}


<div class="form-row align-items-center" data-controller='providers'>
    <div class="col-auto m-2">
        <label for="id_name">Name:</label>
        <input type="text" value="{{object.name}}" name='name' maxlength='100' required id='id_name'>
    </div>
    <div class="col-auto m-2">
        <label for="id_icon">Icon:</label>
        <input type="text" value="{{object.icon}}" name='icon' maxlength='40' required id='id_icon' data-action='keyup->providers#getIcon'>
        <span style='margin-left: 20px' id='icon_value'></span>
    </div>
    <div class="col-auto m-2">
        <label for="id_color">Color:</label>
        <input type="text" value="{{object.color}}" name='color' maxlength='8' required id='id_color' data-providers-target='color'>
    </div>
    <div class="col-auto m-2">
        <label for="id_shortcut">Shortcut:</label>
        <input type="text" value="{{object.shortcut}}" name='shortcut' maxlength='10' required id='id_shortcut'>
    </div>
    <div class="col-auto m-2">
        <label for="id_base_url">Base URL:</label>
        <input type="text" value="{{object.base_url}}" name='base_url' maxlength='200' required id='id_base_url'>
    </div>
    <div class="col-auto m-2">
        <input type="submit" value="Save" class='btn btn-primary'>
    </div>
</div>

</form>

{% endblock card_body %}

templates/productivity/taskaddonprovider_list.html
{% extends '_card.html' %}

{% block title %} Addon Providers {% endblock title %}  

{% block card_body %}


<div class="row" data-controller='providers'>
    {% for prov in object_list %}
        <div class="col-md-3 provider">
            <span data-providers-target='icon' class='provider_icon' data-icon="{{prov.icon}}"></span>
            <a href="{% url 'prod:providers_update' prov.id %}"> {{prov.name}} </a>
        </div>
    {% endfor %}
</div>


{% endblock card_body %}

templates/productivity/week.html
{% extends "base.html" %}

{% block content %}

<div data-controller="week">
    <div class="row my-lg-4 my-md-2 week_stats" style="order: 1">
        <div class="col-sm-6 col-lg-3">
            <div class="card">
                <div class="card-body">
                    <div class="text-value-lg">{{stats.task_count}}</div>
                    <div>Total Tasks</div>
                    <div class="progress progress-xs my-2">
                        <div class="progress-bar bg-gradient-info" role="progressbar"
                            style="width: {{stats.task_count_ratio}}%" aria-valuenow="{{stats.task_count}}"
                            aria-valuemin="0" aria-valuemax="25"></div>
                    </div><small class="text-muted">You have a target of at least 25 tasks per week</small>
                </div>
            </div>
        </div>

        <div class="col-md-3 col-sm-4" style="order: 2">
            <div class="card">
                <div class="card-body text-center">
                    <div class="small text-uppercase font-weight-bold" style="color: #{{stats.max_project.0.color}}">
                        {{stats.max_project.0.name}}</div>
                    <div class="text-value-xl py-3">{{stats.max_project.1}}</div>
                    <div class="c-chart-wrapper mx-auto" style="height:40px;width:80px" id="sparkline-project"
                         data-week-series="{% for i in stats.counts_pro %} {{i}}, {% endfor%}" data-week-legend='tasks per project' 
                         data-week-categories="{% for pro in stats.projects%} {{pro}}, {%endfor%}"
                         data-week-target="plot">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-3 col-sm-4" style="order: 3">
            <div class="card">
                <div class="card-body text-center">
                    <div class="text-muted small text-uppercase font-weight-bold">{{stats.max_category.0.emoji}}
                        {{stats.max_category.0.name}}</div>
                    <div class="text-value-xl py-3">{{stats.max_category.1}}</div>
                    <div class="c-chart-wrapper mx-auto" style="height:40px;width:80px" id="sparkline-categories"
                         data-week-series="{% for i in stats.counts_cat %} {{i}}, {% endfor%}" data-week-legend='tasks per category' 
                         data-week-categories="{% for cat in stats.projects%} {{cat}}, {%endfor%}"
                         data-week-target="plot">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-4" style="order: 4">
            <div class="card">
                <div class="card-body text-center">
                    <div class="text-muted small text-uppercase font-weight-bold">{{stats.max_day.0}}</div>
                    <div class="text-value-xl py-3">{{stats.max_day.1}}</div>
                    <div class="c-chart-wrapper mx-auto" style="height:40px;width:80px" id="sparkline-days"
                         data-week-series="{% for i in stats.counts_array %} {{i}}, {% endfor%}" 
                         data-week-legend='tasks per day' 
                         data-week-categories="['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']"
                         data-week-target="plot">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-group my-2">
        {% for day, tasks in stats.days.items %}
        <div class="card {% if forloop.first or forloop.last %} weekend hidden {% endif %}" {% if forloop.first or forloop.last %} data-week-target='weekendDays' {% endif %} {% if forloop.first %}
            style="order: 2" {% endif %}>
            <h2 class='card-header'>{{day}}</h2>
            <div class="card-body">
                <ul class='list-unstyled'>
                    {% for task in tasks %}
                    {% if task.category.name == 'Task' %}
                    {% ifchanged task.category_id %}
                    <br>
                    {% endifchanged %}
                    {% endif %}

                    <li> {{task.category.emoji}}
                        <span class="tsk-text" style="display: inline-block;">
                            {{task.rich_text|safe}}
                        </span>

                        {% if task.project %}
                        <strong style='color: #{{task.project.color}}' class='project'>
                            {{task.project}}
                        </strong>
                        <span class='addons ml-3 d-inline-block'>
                            {% if task.taskaddon_set.all %}
                                {% for addon in task.taskaddon_set.all %}
                                <a target="_blank" href='{{addon.url}}' class="addon py-0">
                                    <img class='simpleicon' data-action='load->tasks#fixSimpleIconColor' data-color="#{{addon.provider.color}}"
                                        height="16" width="16"
                                        src="https://unpkg.com/simple-icons@v2/icons/{{addon.provider.icon}}.svg" />
                                </a>
                                {% endfor %}
                            {% endif %}
                        </span>
                        <hr>
                        {% ifchanged task.category_id %}
                        <br>
                        {% endifchanged %}
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-footer">Tasks: <strong>{{tasks.count}}</strong> </div>
        </div>
        {% endfor %}
    </div>
    <button id='weekdays' class='btn btn-primary btn-refresh' data-action="click->week#toggleWeekends" data-toggle="tooltip" data-placement="left"
        title="Include Weekends?">
        <i class="fas fa-calendar"></i>
    </button>
    <a href="{% url 'prod:this_week' %}?week_no={{week_no|add:"-1"}}" class="btn btn-pill-primary nav-button previous">
        <i class="fas fa-chevron-left fa-2x"></i>
    </a>
    <a href="{% url 'prod:this_week' %}?week_no={{week_no|add:"1" }}" class="btn btn-pill-primary nav-button next">
        <i class="fas fa-chevron-right fa-2x"></i>
    </a>
</div>
{% endblock content %}