backups/urls.py
from django.contrib import admin
from django.urls import path, include
from productivity.views import home
from rest_framework.routers import DefaultRouter
from productivity import api


router = DefaultRouter()
router.register('categories', api.CategoryViewSet)
router.register('projects', api.ProjectViewSet)
router.register('tasks', api.TaskViewSet)
router.register('addons', api.TaskAddonViewSet)
router.register('addonproviders', api.TaskAddonProviderViewSet)

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('backups/', include('logs.urls')),
    path('prod/', include('productivity.urls')),
    path('profile/', include('profiles.urls')),
    path('sync/', include('sync.urls')),
    path('api/', include(router.urls)),
    path('api/jira', api.JiraWebhook.as_view())
]

logs/urls.py
from django.urls import path

from logs import views

app_name = 'logs'

urlpatterns = [
    path('api/pr', views.Changelog.as_view()),
    path('api/', views.BackUpList.as_view()),
    path('prs/', views.pr_list, name='prs'),
    path('', views.BackUpListView.as_view(), name='backups')
]

sync/urls.py
from django.urls import path

from sync import views
from sync import api

app_name = 'sync'
urlpatterns = [
     path('todoist/', views.todoist_home, name='todoist'),
     path('todoist/link/<int:tid>/project/<int:pid>', views.link_todoist_to_local_project,
          name="todoist-link-project"),
     path('todoist/link/<int:tid>/label/<int:cid>', views.link_todoist_to_local_categories,
          name="todoist-link-category"),
     path('todoist/sync/tasks', views.manual_todoist_sync, name='todoist-sync'),
     path("todoist/webhook", api.TodoistWebhook.as_view(), name="todoist_webhook"),
     path('uptimerobot/monitors', views.uptimerobot_status, name='uptimerobot'),
     path("github/", views.github_repos, name='github'),
     path("github/list", views.get_repo_list, name='github_list'),
     path("github/watch/<str:org>/<str:repo>", views.watch_togggle_repo, name='watch-repo')
]

sync/models.py
from django.contrib.auth.models import User
from django.db import models

from productivity.models import Category, Project, Task


class Sync(models.Model):
    """Implements the Sync job logging model"""
    INTEGRATIONS = [(0, 'Todoist'), (1, 'Google'), (2, 'Github')]
    created_at = models.DateTimeField(auto_now_add=True)
    finished_at = models.DateTimeField(blank=True, null=True)
    integration = models.IntegerField(choices=INTEGRATIONS)
    finished = models.BooleanField(default=False)
    user = models.ForeignKey(User, verbose_name='syncs', on_delete=models.CASCADE)


class PullRequest(models.Model):
    """Model that represents gh prs"""
    number = models.IntegerField()
    html_url = models.URLField(null=True, blank=True)
    title = models.CharField(max_length=400, default='Pull Request')
    opened_by = models.CharField(max_length=300, default='gh-user')
    user_url = models.URLField(null=True, blank=True)
    status = models.CharField(max_length=50, default='open')
    repo_name = models.CharField(max_length=100)
    repo_full_name = models.CharField(max_length=200)
    private = models.BooleanField(default=True)
    created_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    closed_at = models.DateTimeField(blank=True, null=True)
    merged_at = models.DateTimeField(blank=True, null=True)
    task_created = models.BooleanField(default=False)

    def create_task(self) -> None:
        """Creates a Task for a merged PR"""
        if self.task_created:
            return None

        cat = Category.objects.get(name="task")
        pro = Project.objects.get(name='default')

        try:
            repo = Repository.objects.get(name=self.repo_full_name)
        except Repository.DoesNotExist:
            pass
        else:
            if repo.project:
                pro = repo.project

        Task.objects.create(
            category=cat,
            project=pro,
            task=f"**Merged PR** -> *{self.title}* at `{self.repo_full_name}` gh:{self.html_url}"
        )
        self.task_created = True
        return None

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None) -> None:
        """Overrides the default method to check if a task must be created.

        NOTE: New task needs to be created only for newly merged PRs
        """
        check = False
        if not (
            old := PullRequest.objects.filter(pk=getattr(self, "pk", None)).first()
        ):
            check = True
        elif old.status != self.status:
            check = True

        if check and self.status == 'closed' and self.merged_at:
            self.create_task()

        super().save(force_insert=force_insert, force_update=force_update, using=using,
                     update_fields=update_fields)

    def __str__(self):
        return self.title + ' from ' + self.repo_name

    class Meta:
        unique_together = ['number', 'repo_name']


class Repository(models.Model):
    """Implements the model repository"""
    name = models.CharField(max_length=200, unique=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True,
                                related_name="repos")
    private = models.BooleanField(default=False)
    watch = models.BooleanField(default=False)

    class Meta:
        ordering = ('-watch', 'name')

    def __str__(self):
        return self.name

    @property
    def link(self) -> str:
        return f"https://github.com/{self.name}"

sync/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from sync.models import Repository
from productivity.models import Category, Project
from sync import tasks
from sync.decorators import todoist
from sync.integrations.uptimerobot.client import UptimeRobot as Uptime
from sync.tasks import import_github_repos


@login_required
@todoist(settings_url='/profile/settings')
def todoist_home(request):
    """Todoist wizard.
    It provides an interface to link local projects
    with todoist projects for seamless sync.
    """
    return render(request, "sync/todoist.html", {'sets': tasks.todoist_secondary(request.user.id)})


@login_required
def link_todoist_to_local_project(request, tid, pid):
    """Links todoist projects to local projects.

    Args:
    tid (int): Todoist Project Id
    pid (int): Local Project Id

    If the pid is zero it just unlinks the todoist project
    from the linked project.
    """
    Project.objects.filter(todoist_id=tid).update(todoist_id=None)
    if pid:
        project = Project.active.get(pk=pid)
        # project = get_object_or_404(Project, pk=pid)
        project.todoist_id = tid
        project.save(update_fields=['todoist_id'])
    if request.is_ajax():
        return JsonResponse({'ok': True, 'tid': tid, 'pid': pid})
    return redirect('/sync/todoist/')


@login_required
def link_todoist_to_local_categories(request, tid, cid):
    """Links todoist labels to local categories.

    Args:
    tid (int): Todoist Label Id
    cid (int): Local Category Id

    If the pid is zero it just unlinks the todoist labels
    from the linked project.
    """
    Category.objects.filter(todoist_id=tid).update(todoist_id=None)
    if cid:
        label = get_object_or_404(Category, pk=cid)
        label.todoist_id = tid
        label.save(update_fields=['todoist_id'])
    if request.is_ajax():
        return JsonResponse({'ok': True, 'tid': tid, 'cid': cid})
    return redirect('/sync/todoist/')


@login_required
def manual_todoist_sync(request):
    """Performs a simple manual sync."""
    tasks.todoist_sync_completed_tasks(request.user.id)
    return JsonResponse({'status': 200, 'message': 'Sync finished successfully'})


@login_required
def uptimerobot_status(request):
    """Checks the uptime robot and returns their status"""
    return render(request, "sync/uptime.html", {'monitors': Uptime().get_monitors()})


@login_required
def github_repos(request):
    """Lists github repos for the request.user."""
    if not cache.get(f"github_repo_sync_user_{request.user.id}"):
        import_github_repos(uid=request.user.id)
    repo_list = Repository.objects.all()
    return render(request, "sync/github.html", {'repos': repo_list})


@login_required
def get_repo_list(request):
    """Renders the partial for the repos list."""
    repo_list = Repository.objects.all()
    return render(request, "sync/_repo_list.html", {'repos': repo_list})


@require_POST
@login_required
def watch_togggle_repo(_, org: str, repo: str):
    """Toggles the watch/unwatch attribute for the given repo."""
    name = f"{org}/{repo}"
    repository = get_object_or_404(Repository, name=name)
    repository.watch = not repository.watch
    repository.save(update_fields=['watch'])
    message = f"Syn is turned {'on' if repository.watch else 'off'} for {name}"
    return JsonResponse({'repo': repo, 'message': message, 'watch': repository.watch})

templates/sync/_repo.html
<div class="repo mx-2 my-3 col-md-5 col-sm-12" data-name='{{repo.name}}' data-github-target="repo">
    <span class="repo_icon{% if repo.private %} private text-warning{% endif %}" data-github-target="repoIcon" ></span>
    <a class="repo_name" href="https://github.com/{{repo.name}}" target="_blank">{{repo.name}}</a>
    <span class="repo-status" data-watch="{{repo.watch}}">
        {% if repo.watch %}
            <span class="icon">
                <i class="fas fa-check text-success"></i>
            </span>
            <button class="btn btn-danger btn-sm btn-watch" data-repo="{{repo.name}}" data-action="click->github#toggleRepoStatus">Stop Watching</button>
        {% else %}
            <button class="btn btn-info btn-sm" data-repo="{{repo.name}}" data-action="click->github#toggleRepoStatus">Watch</button>
        {% endif %}
    </span>
</div>

templates/sync/_repo_list.html
{% for repo in repos %}
    {% include "sync/_repo.html" %}
{% empty %}
    <li><i>No repositories found...</i></li>
{% endfor %}

templates/sync/github.html
{% extends '_card.html' %}

{% block title %}
Githhub Wizard
{% endblock title %}

{% block card_body %}
<h1 class="card-name">Github Configuration</h1>

<div class="container" data-controller='github'>

<div class="row">
    <div class="col-md-12">
        <i class="fab fa-github fa-2x"></i>
        <input type="text" class="input" name="repo_search" id="repo_search" placeholder="Search for github repos" data-action="keydown->github#searchRepos" data-github-target="repoSearch">
    </div>
</div>

<div class="row repos" data-github-target='repoList'>
    {% include "sync/_repo_list.html" %}
</div>

</div>
{% endblock card_body %}

templates/sync/todoist.html
{% extends '_card.html' %}

{% block title %}
Todoist Wizard
{% endblock title %}

{% block card_body %}

<h1 class="card-name">Projects</h1>

<ul>
    {% for match in sets.projects %}
        <li> <span style="color: {{match.0.color_hex}}">{{match.0.name}}</span> -> <span style="color: #{{match.1.color}}">{{match.1}}</span>
            {% if match.1.todoist_id == match.0.id %} 
                <span class="badge bg-success rounded-pill"><i class="fas fa-check"></i> Linked</span>
                <a href="{% url 'sync:todoist-link-project' match.0.id 0 %}" class="btn btn-ghost-warning btn-pill btn-sm">Unlink</a> 
            {% else %} 
                <a href="{% url 'sync:todoist-link-project' match.0.id match.1.id %}" class="btn btn-ghost-info btn-pill btn-sm">Link</a> 
            {% endif %} 
        </li>
    {% endfor %}
</ul>

<h1 class="card-name">Labels</h1>

<table class="table">
    <thead>
        <tr>
            <th>Todoist Label</th>
            <th>Category</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for match in sets.categories %}
            <tr>
                <td>{{match.0.name}}</td>
                <td>{{match.1}}</td>
                <td>
                    {% if match.1.todoist_id == match.0.id %} 
                        <span class="badge bg-success rounded-pill"><i class="fas fa-check"></i> Linked</span>
                        <a href="{% url 'sync:todoist-link-category' match.0.id 0 %}" class="btn btn-ghost-warning btn-pill btn-sm">Unlink</a> 
                    {% else %} 
                        <a href="{% url 'sync:todoist-link-category' match.0.id match.1.id %}" class="btn btn-ghost-info btn-pill btn-sm">Link</a> 
                    {% endif %}
                
                </td>

            </tr>  
    
        {% endfor %}
    </tbody>

</table>


{% endblock card_body %} 

templates/sync/uptime.html
<ul class='uptime'>
    {% for monitor in monitors.monitors %}
        <li><strong>{{monitor.friendly_name}}: </strong> 
            <span data-status="{{monitor.status}}" data-toggle="tooltip" data-placement="top" title="test">
                <i class="fas fa-circle {%if monitor.status == 2  %} text-success {%elif monitor.status > 7 %} text-danger {%else%} text-warning {%endif%}">
                </i>
            </span>
        </li>
    {% endfor %}
</ul>

<script>
statuses = {"0": "paused", "1": "not check yet", "2": "up", "8": "seems down", "9": "down"}
function set_tooltip(){
    console.log($(this))
    $(this).title = statuses[$(this).dataset.status]
}
$('ul.uptime li span').each(function() {
    this.title = statuses[this.dataset.status]
})
</script>