backups/urls.py
from django.contrib import admin
from django.urls import path, include
from productivity.views import home
from rest_framework.routers import DefaultRouter
from productivity import api


router = DefaultRouter()
router.register('categories', api.CategoryViewSet)
router.register('projects', api.ProjectViewSet)
router.register('tasks', api.TaskViewSet)
router.register('addons', api.TaskAddonViewSet)
router.register('addonproviders', api.TaskAddonProviderViewSet)

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('backups/', include('logs.urls')),
    path('prod/', include('productivity.urls')),
    path('profile/', include('profiles.urls')),
    path('sync/', include('sync.urls')),
    path('api/', include(router.urls)),
    path('api/jira', api.JiraWebhook.as_view())
]

logs/urls.py
from django.urls import path

from logs import views

app_name = 'logs'

urlpatterns = [
    path('api/pr', views.Changelog.as_view()),
    path('api/', views.BackUpList.as_view()),
    path('prs/', views.pr_list, name='prs'),
    path('', views.BackUpListView.as_view(), name='backups')
]

productivity/urls.py
from django.urls import path

from productivity import views

app_name = 'prod'

urlpatterns = [
    path('today/', views.today, name='today'),
    path('week/', views.this_week, name='this_week'),
    path('today/refresh', views.tasks_today, name='refresh'),
    path('category/find', views.find_category, name='find_category'),
    path('category/create', views.create_category, name='create_category'),
    path('defaults/', views.tasks_in_default, name='defaults'),
    path('project/find', views.find_project, name='find_project'),
    path('project/create', views.create_project, name='create_project'),
    path('tasks/create', views.create_task, name='task_create'),
    path('tasks/delete', views.delete_task, name='task_delete'),
    path('tasks/<int:tid>/addon', views.add_new_addon, name='task_addon'),
    path('tasks/project/<str:pro>', views.find_by_project, name='by_project'),
    path('tasks/fu/<int:task>/<str:field>/<int:val>', views.task_fast_update, name='tfu'),
    path('tasks/fu/<int:task>/<str:field>/<str:val>', views.task_fast_update, name='tfu'),
    path('emails/', views.read_mails, name='mails'),
    path('emails/import', views.import_emails, name='import_mails'),
    path('events/import', views.import_events, name='import_events'),
    path('providers/create', views.CreateAddonProviderView.as_view(), name='provider_create'),
    path('providers/', views.ListAddonProviderView.as_view(), name='providers_list'),
    path('providers/update/<int:pk>', views.UpdateAddonProviderView.as_view(), name='providers_update'),
    path('projects/list', views.ProjectFastUpdateListView.as_view(), name='projects_quicklist'),
    path('categories/list', views.CategoryFastUpdateListView.as_view(), name='categories_quicklist'),
    path('task/<int:task>/list', views.task_text_fast_update_view, name='text_quicklist'),
    path("projects/", views.ProjectsView.as_view(), name="projects"),
    path("projects/new", views.generate_new_project, name='generate_project'),
    path("projects/delete/<int:pro>", views.delete_project, name='delete_project'),
    path("projects/partial", views.ListProjectView.as_view(), name="projects_list_partial"),
    path('projects/fu/<int:pro>/<str:field>/<int:val>', views.project_fast_update, name='pfu'),
    path('projects/fu/<int:pro>/<str:field>/<str:val>', views.project_fast_update, name='pfu'),
    path('projects/update/template/<int:pro>', views.project_update_view, name='project_update'),
    path("categories/", views.CategoriesView.as_view(), name="categories"),
    path("categories/new", views.generate_new_category, name='generate_category'),
    path("categories/partial", views.ListCategoriesView.as_view(), name="categories_list_partial"),
    path("categories/delete/<int:cat>", views.delete_category, name='delete_category'),
    path('categories/update/template/<int:cat>/<str:field>', views.category_update_view, name='cat_update'),
    path('categories/fu/<int:cat>/<str:field>/<str:val>', views.category_fast_update, name='cfu'),
    ]

profiles/urls.py
from django.urls import path

from profiles import views

app_name = 'profiles'
urlpatterns = [
    path('avatar/', views.AvatarUpdateview.as_view(), name='avatar'),
    path('refresh_token/', views.refresh_token, name='refresh_token'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('notification/<int:id>', views.visit_notification, name='notification')
]

sync/urls.py
from django.urls import path

from sync import views
from sync import api

app_name = 'sync'
urlpatterns = [
     path('todoist/', views.todoist_home, name='todoist'),
     path('todoist/link/<int:tid>/project/<int:pid>', views.link_todoist_to_local_project,
          name="todoist-link-project"),
     path('todoist/link/<int:tid>/label/<int:cid>', views.link_todoist_to_local_categories,
          name="todoist-link-category"),
     path('todoist/sync/tasks', views.manual_todoist_sync, name='todoist-sync'),
     path("todoist/webhook", api.TodoistWebhook.as_view(), name="todoist_webhook"),
     path('uptimerobot/monitors', views.uptimerobot_status, name='uptimerobot'),
     path("github/", views.github_repos, name='github'),
     path("github/list", views.get_repo_list, name='github_list'),
     path("github/watch/<str:org>/<str:repo>", views.watch_togggle_repo, name='watch-repo')
]

productivity/models.py
from functools import cached_property

from markdown import markdown

from django.conf import settings
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.timezone import now


class TodoistManager(models.Manager):
    def get_queryset(self) -> models.QuerySet:
        return super(TodoistManager, self).get_queryset().filter(todoist_id__isnull=False)


class Category(models.Model):
    """The categories of the projects."""
    name = models.CharField(max_length=20, unique=True)
    emoji = models.CharField(max_length=10)
    # TODO: Make this a unique together when it will relate to the user
    todoist_id = models.BigIntegerField(blank=True, null=True, unique=True)
    objects = models.Manager()
    todoist = TodoistManager()

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.emoji + " " + self.name

    @cached_property
    def tasks_count(self) -> int:
        """Total number of tasks associated with the category."""
        return self.task_set.count()


class ActiveProjectManager(models.Manager):
    """Manager that gets only active projects by default"""
    def get_queryset(self) -> models.QuerySet:
        return super().get_queryset().filter(is_active=True)


class Project(models.Model):
    """The tasks project model."""
    name = models.CharField(max_length=20, unique=True)
    color = models.CharField(max_length=8)
    # TODO: Make this a unique together when it will relate to the user
    todoist_id = models.BigIntegerField(blank=True, null=True, unique=True)
    objects = models.Manager()
    todoist = TodoistManager()
    is_active = models.BooleanField(default=True)
    active = ActiveProjectManager()

    def __str__(self) -> str:
        return "#" + self.name

    def remove_hex_prefix(self):
        """Removes the # on colors"""
        self.color = self.color.replace("#", "")

    @cached_property
    def tasks_count(self) -> int:
        """Total number of tasks associated with the project."""
        return self.task_set.count()

    @cached_property
    def repos_count(self) -> int:
        """Total number of repos associated with the project."""
        return self.repos.count()


class Task(models.Model):
    """Model to log tasks within the day"""
    created_at = models.DateTimeField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    task = models.CharField(max_length=400)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True,
                                blank=True)
    objects = models.Manager()
    # TODO: Make this a unique together when it will relate to the user
    todoist_id = models.BigIntegerField(blank=True, null=True)
    todoist = TodoistManager()

    class Meta:
        ordering = ['category', 'created_at']

    def __str__(self) -> str:
        return self.category.emoji + self.task

    def save(self, *args, **kwargs):
        if self.created_at is None:
            self.created_at = now()
        super(Task, self).save(*args, **kwargs)

    @property
    def rich_text(self) -> str:
        return markdown(self.task)

    def has_addon_in_task(self):
        """Checks whether the task has an addon inserted"""
        return ":" in self.task

    def extract_addons(self):
        for word in self.task.split(" "):
            if ":" in word:
                try:
                    sh = word.split(":")
                    prov = TaskAddonProvider.objects.get(shortcut=sh[0])
                except (ObjectDoesNotExist, MultipleObjectsReturned):
                    pass
                else:
                    self.create_addon(prov, word)
                finally:
                    self.task = self.task.replace(word, "")

        self.save()

    def create_addon(self, prov, word):
        sh = word.split(":")
        if sh[1] in ["", " ", None]:
            return None
        if sh[1].startswith('http'):
            TaskAddon.objects.create(
                task=self, provider=prov, url=word.split(sh[0] + ":")[1],
            )
        else:
            TaskAddon.objects.create(
                task=self, provider=prov, uid=word.split(sh[0] + ":")[1],
            )
        return None

    @property
    def pendulum_dt(self):
        """Returns the datetime in a pendulum class"""
        from pendulum.parser import parse
        return parse(str(self.created_at)).in_timezone(settings.TIME_ZONE)

    @property
    def date(self) -> str:
        """Returns the date the task was created"""
        return self.pendulum_dt.to_date_string()

    @property
    def time(self) -> str:
        """Returns the time the task was created"""
        return self.pendulum_dt.to_time_string()

    @property
    def datetime(self) -> str:
        """Returns the full datetime the issue was created"""
        return self.pendulum_dt.to_datetime_string()


class Gmail(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    from_address = models.CharField(max_length=200)
    subject = models.CharField(max_length=500)
    done = models.BooleanField(default=False)
    thread_id = models.CharField(max_length=50, unique=True)


class TaskAddonProvider(models.Model):
    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=40)
    color = models.CharField(max_length=8)
    shortcut = models.CharField(max_length=10, null=True, blank=True)
    base_url = models.URLField()

    @staticmethod
    def get_absolute_url() -> str:
        """Returns the list url of the model."""
        return reverse("prod:providers_list")

    def __str__(self):
        """Returns the representation string for the model."""
        return self.name

    def show_base_url(self, task):
        """Renders the template url into the file link."""
        return self.base_url.format(task=task)

    def remove_hex_prefix(self):
        """Removes the # on colors"""
        self.color = self.color.replace("#", "")


class TaskAddon(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    provider = models.ForeignKey(TaskAddonProvider, on_delete=models.CASCADE)
    uid = models.CharField(max_length=200)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.provider.name + ' for ' + self.task.__str__()

    def set_params(self) -> None:
        if self.url:
            self.uid = self.url.split('/')[-1]
        if self.uid and self.provider and not self.url:
            self.url = self.provider.show_base_url(self.task) + self.uid
        self.save()


@receiver(post_save, sender=Task)
def create_task_addon(sender, instance, created, **kwargs):
    if instance.has_addon_in_task() and instance.project:
        instance.extract_addons()


@receiver(post_save, sender=TaskAddon)
def set_addon_url(sender, instance, created, **kwargs):
    if created:
        instance.set_params()


@receiver(pre_save, sender=TaskAddonProvider)
@receiver(pre_save, sender=Project)
def removes_prefix_from_colors(sender, instance, **kwargs):
    instance.remove_hex_prefix()

templates/_card.html
{% extends 'base.html' %}


{% block content %}

<div class="row justify-content-center py-5">
    <div class="card col-md-6">
        <div class="card-body">
            <h3 class="card-name pt-2 pb-4">{% block title %} Card Title {% endblock  %}</h3>
            {% block card_body %}

            {% endblock card_body %}
        </div>
    </div>
</div>


{% block extra %}
{% endblock extra %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BackUp Logs</title>
    {% load static %}
    {% load logs_extras %}
    {% load profile_extras %}
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="shortcut icon" href="/upload/favicon.png" type="image/x-icon">  
    <script src="{% static 'main.js' %}"></script>
  </head>
  <body class="c-app">
  <div class="c-wrapper">
      <header data-controller='theme' class="c-header c-header-light px-3">
        <a class="c-header-brand">BackUp</a>
        <ul class="c-header-nav mr-auto">
          <li class="c-header-nav-item">
            <a class="c-header-nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
           <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Productivity
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'prod:today' %}">Today</a>
              <a class="dropdown-item" href="{% url 'prod:this_week' %}">Week</a>
              <a class="dropdown-item" href="{% url 'prod:defaults' %}">Defaults</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'prod:mails' %}">Emails</a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'prod:providers_list' %}" class="dropdown-item">Addon Templates</a>
              <a href="{% url 'prod:categories' %}" class="dropdown-item"> Categories</a>
              <a href="{% url 'prod:projects' %}" class="dropdown-item"> Projects</a>
            </div>
          </li>
          <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link dropdown-toggle" id="integrationsDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              Integrations
            </a>
            <div class="dropdown-menu" aria-labelledby="integrationsDropdown">
              <a href="{% url "sync:github" %}" class="dropdown-item">Github</a>
              <a class="dropdown-item" href="{% url 'sync:todoist' %}">Todoist</a>
            </div>
          </li>
          <li class="c-header-nav-item"><a href="/admin" class="c-header-nav-link">Admin</a></li>
        </ul>
        <ul class="c-header-nav mfs-auto">
          <li class="c-header-nav-item">
            <button data-theme-target='switch' data-action='theme#switchTheme'  id='dark' class="c-header-nav-btn mr-2" data-toggle="tooltip" data-placement="bottom" title="Toggle Ligth/Dark Mode">
              <i class="fas fa-moon" style='width:16px; height:16px;'></i>
            </button>
          </li>
          {% user_notifications user as notifications%}
          <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-btn mr-2" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell" style='width:18px; height:18px;'></i>
                {% if notifications %}
                  <span class="badge badge-danger mfs-auto">{{notifications.count}}</span>
                {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
              {% for notif in notifications %}
                <a class="dropdown-item" href="{{ notif.get_absolute_url }}">
                  {{notif.text}}
                </a>
              {% empty %}
                <a class="dropdown-item"><i>No unread notifications</i></a>
              {% endfor %}
            </div>
          </li>
          <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <div class="c-avatar">
                <img class="c-avatar-img" src="{% if user.profile.avatar %} {{user.profile.avatar.url}} {% else %} /upload/avatar.png {% endif %}" alt="user@email.com">
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
              <div class="dropdown-header bg-light py-2">
                <strong>Account</strong>
              </div>
              <a class="dropdown-item" href="{% url 'prod:mails' %}">
                <i class="fas fa-envelope c-icon mfe-2"></i>
                Emails
                <span class="badge badge-danger mfs-auto">{% load_mail %}</span>
              </a>
              <div class="dropdown-header bg-light py-2">
                <strong>Settings</strong>
              </div>
              <a class="dropdown-item" href="{% url 'profiles:settings'%}">
                <i class="fas fa-cog c-icon mfe-2"></i>
                Settings
              </a>
              <a class="dropdown-item" href="{% url 'profiles:settings'%}">
                <i class="fas fa-code-branch c-icon mfe-2"></i>
                {% version %}
              </a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'admin:logout' %}">
                <i class="fas fa-sign-out-alt c-icon mfe-2"></i>
                Logout
              </a>
          </div>
        </li>
      </ul>
    </header>
    <div class="container-fluid">
    {% block content %}
    
    {% endblock content %}
    </div>
  </div>
    <script async src="https://kit.fontawesome.com/51ae16f369.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
    {% block script %}

    {% endblock script %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<style>
.card{
    height: 100%;
}
#eventslist li{
    margin: 10px;
}
</style>
<div class="container" data-controller="home">
    <div class="row my-5">
        <div class="col-md-8 col-sm-12 my-3">
            <div class="card">
                <div class="card-header">Done Today <a href="{% url 'prod:today' %}" class="btn btn-outline-primary btn-sm float-right">Go</a></div>
                    <div class="card-body">
                        <ul class='list-unstyled'>
                            {% for task in tasks %}
                                <li class='tsk {{task.project.name}}'> {{task.category.emoji}} 
                                    <span class="tsk-text" style="display: inline-block;">
                                        {{task.rich_text|safe}} 
                                    </span>
                                    <span class='project' style='color: #{{task.project.color}}'>
                                        {{task.project}}
                                    </span>
                                    <span class='addons ml-3 d-block'>
                                        {% if task.taskaddon_set.all %}
                                            {% for addon in task.taskaddon_set.all %}
                                            <a target="_blank" href='{{addon.url}}' class="addon py-0">
                                                <img class='simpleicon' data-action='load->tasks#fixSimpleIconColor' data-color="#{{addon.provider.color}}"
                                                    height="16" width="16"
                                                    src="https://unpkg.com/simple-icons@v2/icons/{{addon.provider.icon}}.svg" />
                                            </a>
                                            {% endfor %}
                                        {% endif %}
                                    </span>
                                </li>
                                {% empty %}
                                <li><i>No tasks logged yet</i></li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 my-3">
            <div class="card">
                <div class="card-header">
                    Backups Status
                    <a href="{% url 'logs:backups'%}" class="btn btn-outline-primary btn-sm float-right">See All</a>
                </div>
                <div class="card-body">
                    <ul>
                        {% for app,st in status.items %}
                            <li><b>{{app}}</b>: {% if st %} <i class="fas fa-check text-success"></i> {% else %} <i class="fas fa-times text-danger"></i> {% endif %}</li>
                        {% empty%}
                            <li><i>No backups logged yet</i></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12 my-3 {% if not user.profile.settings.gh_pr %}hidden{%endif%}">
            <div class="card">
                <div class="card-header">
                    Pending PRs
                    <a class='btn btn-primary btn-sm float-right' style='color: #fff' data-action="home#forcePRList">
                        <i class="fas fa-sync"></i>
                    </a>
                </div>
                <div id="prs" class="card-body" data-home-target="ghPrContainer"></div>
            </div>
        </div>
        <div class="col-md-6 col-sm-12 my-3 {% if not user.profile.settings.gcalendar %}hidden{%endif%}">
            <div class="card">
                <div class="card-header">
                    Coming Events
                    <a class='btn btn-primary btn-sm float-right' style='color: #fff' data-action="home#GoogleCalendar">
                        <i class="fas fa-sync"></i>
                    </a>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled" data-home-target="gCalendarContainer" id='eventsList'>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 my-3 {% if not user.profile.settings.uptime_robot %}hidden{%endif%}">
            <div class="card">
                <div class="card-header">Pages Status</div>
                <div id='uptime' class="card-body" data-home-target="upTimeContainer"></div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}